framework:
  version: "0.0.1"

api:
  host: 127.0.0.1
  port: 8000
  server: "https://api.vk.com/"
  version: "5.199"
  wait: 25

JSON_LOGGER:
  version: 1
  disable_existing_loggers: False
  formatters:
    console:
      (): "logger.formatters.DarkyConsoleFormatter"
      format: "[%(name)s] %(asctime)s (%(levelname)s) %(message)s"
  handlers:
    console:
      level: INFO #изменять для вывода в консоль
      class: "logging.StreamHandler"
      formatter: "console"
  loggers:
    DARKYVK:
      handlers: ["console"]
      level: "DEBUG"
      propagate: False