framework:
  version: "0.0.1"

api:
  host: 127.0.0.1
  port: 8080
  title: DarkyBot VK API
  description: Welcome to the DarkyBot VK API!
  routes:
    ping:
      name: Ping the API
      description: Pings the server and bot's API
    stop:
      name: Stop the bot
      description: Stops the bot and its API
  version: 0.0.1

vk_api:
  server: "https://api.vk.com/"
  version: "5.199"
  wait: 25

JSON_LOGGER:
  version: 1
  disable_existing_loggers: False
  formatters:
    console:
      (): "darky_vk.logger.formatters.DarkyConsoleFormatter"
      fmt: "%(name)s | %(asctime)s | %(levelname)s | %(message)s"
      colored: True
    uvicorn_access_console:
      (): "darky_vk.logger.formatters.UvicornAccessFormatter"
      fmt: "%(name)s | %(asctime)s | %(levelname)s | %(client_addr)s - \"%(request_line)s\" %(status_code)s"
      colored: True
  handlers:
    console:
      level: DEBUG
      class: "logging.StreamHandler"
      formatter: "console"
    uvicorn_access_console:
      level: DEBUG
      class: "logging.StreamHandler"
      formatter: "uvicorn_access_console"
  loggers:
    DARKY_API:
      handlers: ["console"]
      level: DEBUG
      propagate: False
    DARKY_VK:
      handlers: ["console"]
      level: DEBUG
      propagate: False
    botlongpoll:
      handlers: ["console"]
      level: DEBUG
      propagate: False
    vk-methods:
      handlers: ["console"]
      level: DEBUG
      propagate: False
    uvicorn.access:
      handlers: ["uvicorn_access_console"]
      level: DEBUG
      propagate: False
    uvicorn.error:
      handlers: ["console"]
      level: WARNING
      propagate: False