framework:
  version: "0.0.1"

api:
  host: 127.0.0.1
  port: 8000
  title: DarkyBot VK API
  description: Welcome to the DarkyBot VK API!
  version: 0.0.1

vk_api:
  server: "https://api.vk.com/"
  version: "5.199"
  wait: 25

JSON_LOGGER:
  version: 1
  disable_existing_loggers: False
  formatters:
    console:
      (): "darky_vk.logger.formatters.DarkyConsoleFormatter"
      fmt: "%(name)s | %(asctime)s | %(levelname)s | %(message)s"
      colored: True
  handlers:
    console:
      level: INFO #изменять для вывода в консоль
      class: "logging.StreamHandler"
      formatter: "console"
  loggers:
    DARKY_API:
      handlers: ["console"]
      level: DEBUG
      propagate: False
    DARKY_VK:
      handlers: ["console"]
      level: DEBUG
      propagate: False
    uvicorn:
      handlers: ["console"]
      level: WARNING
      propagate: False